### PR TITLE
fix: fixed invite to new user by switching email addresses

### PR DESCRIPTION
**Pull request by loydbanks**

### CODE REVIEW

**Comment by paddatrapper** [comment]
How do we send emails from HELIX? Does it use SES?

**Comment by loydbanks** [comment]
> How do we send emails from HELIX? Does it use SES?

Yes, it uses SES. We were using info@seed-platfrom.org for the email which is not a verified identity for SES hence the change.

**Comment by paddatrapper** [comment]
Is noreply_helix@neep.org verified?

**Comment by loydbanks** [comment]
> Is [noreply_helix@neep.org](mailto:noreply_helix@neep.org) verified?

Yes it is.

**Review by paddatrapper — APPROVED** [review]

**Pull request merged**
